### ISSUE TITLE
Joysticks are swapped

### ISSUE THREAD

**Issue by ArcadeTV** [libretro/libretro-o2em#17]
I just installed the core on my retropie setup and wondered why I wasn't able to control most of the games... then I realized that joysticks are swapped when I started 01:Race and controlled the blue car with controller#1.
Dunno if that's an o2em issue or how the controllers are mapped.

**Comment by estefan3112** [comment]
Videopac is infamous for some games to have controllers swapped. I had my Videopac as a kid, and in a game such as Sattelite Attack (UFO), it had to be played with Controller 2. So this is an issue of the console itself. Workaround in Retroarch is depending on what you want to achieve: If you are only into 1 player games, just assign your one joypad to both ports. But if you are also playing 2 player games, such as Laser Wars, you must create game-specific bindings for the swapped games. Hope this helps!
