### ISSUE TITLE
is there a core for ps vita?

### ISSUE THREAD

**Issue by toaster-code** [libretro/libretro-o2em#32]
I found out that psvita version of retroarch does not contain a core for o2em. Can anyone explain why? Am I missing something?

**Comment by twinaphex** [comment]
I think it's been added for Vita now a long time ago. Hopefully this can be closed. Let me know if it doesn't work, you can open another issue then.

**Comment by toaster-code** [comment]
I am reinstalling RetroArch again on my psVita to check if the latest version has the o2em core.
