### ISSUE TITLE
[Feature Request] Core for Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/libretro-o2em#36]
Hi there, just wondering why this core is not available on Retroarch for Wii. Any chance it could be made to work on the Wii? Thanks.

**Comment by twinaphex** [comment]
OK, I added it for Gamecube and Wii, should be in tomorrow's nightlies.

**Comment by Edu789** [comment]
Ok, Thanks.

**Comment by twinaphex** [comment]
Did it work?

**Comment by Edu789** [comment]
Yes, thanks.
