### ISSUE TITLE
can you add OpenDingux

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-o2em#42]
can you add OpenDingux? i would love to have this emulator on my pocket go 2v2

**Comment by jdgleaver** [comment]
This should be possible, but looking through the code it seems the core has significant usability issues right now. I want some degree of 'curation' when it comes to OpenDingux cores, so I wouldn't feel happy releasing for this platform without fixing the obvious general problems. I will try to find some time to work on this later in the week...

**Comment by Cibomatto2002** [comment]
Thank you so much. This was my first console I ever had.

**Comment by Cibomatto2002** [comment]
Maybe you could make it for Retroarch for opendingux

**Comment by jdgleaver** [comment]
Here you go: https://github.com/libretro/libretro-o2em/pull/43

The core has excellent performance on OpenDingux :)
