### ISSUE TITLE
can't change dpad up/down/left/right to analog in retroarch.cfg

### ISSUE THREAD

**Issue by molesmile** [libretro/libretro-o2em#5]
woud be nice to know how we could change dpad to analog. some games (for example nightmare) need have diagonal play directions.
thanks!

this didn't work:
# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line

input_remapping_directory = /opt/retropie/configs/videopac/
input_device = "Zeemote: SteelSeries FREE"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_r_x_minus_axis = "-2"
input_l2_btn = "6"
input_start_btn = "11"
input_exit_emulator_btn = "11"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_r_y_minus_axis = "-3"
input_a_btn = "0"
input_b_btn = "1"
input_reset_btn = "1"
input_down_btn = "h0down"
input_r2_btn = "7"
input_l_x_plus_axis = "+0"
input_l_y_plus_axis = "+1"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_x_btn = "4"
input_menu_toggle_btn = "4"
input_select_btn = "12"
input_enable_hotkey_btn = "12"
input_l_x_minus_axis = "-0"
input_y_btn = "3"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_r_x_plus_axis = "+2"

#include "/opt/retropie/configs/all/retroarch.cfg"

**Comment by AlexFolland** [comment]
L and R are not left and right in the RetroPad abstraction.  They are the shoulder buttons.  You need to use input_player1_up_axis, input_player1_down_axis, input_player1_left_axis, and input_player1_right_axis.

**Comment by molesmile** [comment]
thanks for your reply. this means diagonal axis won't work.

**Comment by AlexFolland** [comment]
I've never heard of a diagonal axis, but it doesn't mean that it's impossible to configure with RetroArch.

For example, you can set input_player1_down_axis and input_player1_right_axis to the same axis value like "+3" or whatever the axis ID number is, and using that direction of that axis on your bizarre controller will use down and right simultaneously.

**Comment by molesmile** [comment]
got it right now:

input_player1_up_axis = -1
input_player1_down_axis = +1
input_player1_left_axis = -0
input_player1_right_axis = +0

**Comment by AlexFolland** [comment]
Good!  Someone can probably close this topic.
