### ISSUE TITLE
bad audio with o2em

### ISSUE THREAD

**Issue by G7200** [libretro/libretro-o2em#7]
Can the audio be improved? It sounds crunchy, maybe a buffer-issue?

**Comment by starquake** [comment]
I noticed the same issue. It sounds like every n milliseconds there is no sound. But very regularly which makes it sound like a low tone. Going to play around with some more settings. See if I can find the cause.

I'm running this on a Raspberry Pi 2 over HDMI

**Comment by starquake** [comment]
Maybe this is the reason:

https://github.com/libretro/libretro-o2em/issues/8
